#!/bin/bash

device=$1

  year=$(date +%Y)
   day=$(date +%j | sed 's,^0*,,')
  hour=$(date +%k)
minute=$(date +%M | sed 's,^0*,,')
second=$(date +%S | sed 's,^0*,,')

: $((day--))

deliverables/bin/scsi cdbw -v2 -d $device -c 10 -z 8  0x3b 1 0 0xc 0 0 0 0 0xc 0   $((year/256)) $((year%256)) $((day/256)) $((day%256)) 0 $hour $minute $second
