/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SCSI_H_RPCGEN
#define _SCSI_H_RPCGEN

#include <rpc/rpc.h>


typedef char byte;
#ifdef __cplusplus 
extern "C" bool_t xdr_byte(XDR *, byte*);
#elif __STDC__ 
extern  bool_t xdr_byte(XDR *, byte*);
#else /* Old Style C */ 
bool_t xdr_byte();
#endif /* Old Style C */ 


struct send_cdb_params {
	char *device;
	char rw;
	struct {
		u_int cdb_len;
		char *cdb_val;
	} cdb;
	struct {
		u_int dat_len;
		char *dat_val;
	} dat;
	int dat_maxlen;
	int stt_maxlen;
	int timeout;
};
typedef struct send_cdb_params send_cdb_params;
#ifdef __cplusplus 
extern "C" bool_t xdr_send_cdb_params(XDR *, send_cdb_params*);
#elif __STDC__ 
extern  bool_t xdr_send_cdb_params(XDR *, send_cdb_params*);
#else /* Old Style C */ 
bool_t xdr_send_cdb_params();
#endif /* Old Style C */ 


struct send_cdb_retval {
	byte status;
	struct {
		u_int dat_len;
		char *dat_val;
	} dat;
	struct {
		u_int stt_len;
		char *stt_val;
	} stt;
};
typedef struct send_cdb_retval send_cdb_retval;
#ifdef __cplusplus 
extern "C" bool_t xdr_send_cdb_retval(XDR *, send_cdb_retval*);
#elif __STDC__ 
extern  bool_t xdr_send_cdb_retval(XDR *, send_cdb_retval*);
#else /* Old Style C */ 
bool_t xdr_send_cdb_retval();
#endif /* Old Style C */ 


#define SCSI_PROG ((u_long)600039074)
#define SCSI_VERS ((u_long)1)

#ifdef __cplusplus
#define SEND_CDB ((u_long)1)
extern "C" send_cdb_retval * send_cdb_1(send_cdb_params *, CLIENT *);
extern "C" send_cdb_retval * send_cdb_1_svc(send_cdb_params *, struct svc_req *);
#define RESET ((u_long)2)
extern "C" int * reset_1(char **, CLIENT *);
extern "C" int * reset_1_svc(char **, struct svc_req *);

#elif __STDC__
#define SEND_CDB ((u_long)1)
extern  send_cdb_retval * send_cdb_1(send_cdb_params *, CLIENT *);
extern  send_cdb_retval * send_cdb_1_svc(send_cdb_params *, struct svc_req *);
#define RESET ((u_long)2)
extern  int * reset_1(char **, CLIENT *);
extern  int * reset_1_svc(char **, struct svc_req *);

#else /* Old Style C */ 
#define SEND_CDB ((u_long)1)
extern  send_cdb_retval * send_cdb_1();
extern  send_cdb_retval * send_cdb_1_svc();
#define RESET ((u_long)2)
extern  int * reset_1();
extern  int * reset_1_svc();
#endif /* Old Style C */ 

#endif /* !_SCSI_H_RPCGEN */
