/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <rpc/types.h>
#include <rpc/xdr.h>

#include "scsi.h"

bool_t
xdr_byte(XDR *xdrs, byte *objp)
{

	 register long *buf;

	 if (!xdr_char(xdrs, objp)) {
		 return (FALSE);
	 }
	return (TRUE);
}

bool_t
xdr_send_cdb_params(XDR *xdrs, send_cdb_params *objp)
{

	 register long *buf;

	 if (!xdr_string(xdrs, &objp->device, ~0)) {
		 return (FALSE);
	 }
	 if (!xdr_char(xdrs, &objp->rw)) {
		 return (FALSE);
	 }
	 if (!xdr_bytes(xdrs, (char **)&objp->cdb.cdb_val, (u_int *)&objp->cdb.cdb_len, 12)) {
		 return (FALSE);
	 }
	 if (!xdr_bytes(xdrs, (char **)&objp->dat.dat_val, (u_int *)&objp->dat.dat_len, ~0)) {
		 return (FALSE);
	 }
	 if (!xdr_int(xdrs, &objp->dat_maxlen)) {
		 return (FALSE);
	 }
	 if (!xdr_int(xdrs, &objp->stt_maxlen)) {
		 return (FALSE);
	 }
	 if (!xdr_int(xdrs, &objp->timeout)) {
		 return (FALSE);
	 }
	return (TRUE);
}

bool_t
xdr_send_cdb_retval(XDR *xdrs, send_cdb_retval *objp)
{

	 register long *buf;

	 if (!xdr_byte(xdrs, &objp->status)) {
		 return (FALSE);
	 }
	 if (!xdr_bytes(xdrs, (char **)&objp->dat.dat_val, (u_int *)&objp->dat.dat_len, ~0)) {
		 return (FALSE);
	 }
	 if (!xdr_bytes(xdrs, (char **)&objp->stt.stt_val, (u_int *)&objp->stt.stt_len, ~0)) {
		 return (FALSE);
	 }
	return (TRUE);
}
